kind: Service
apiVersion: v1
metadata:
  name: adopt-service
  labels:
    name: springboot-postgres-k8s
spec:
  ports:
    - nodePort: 30800
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: adopt
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adopt-deployment
spec:
  selector:
    matchLabels:
      app: adopt
  replicas: 3
  template:
    metadata:
      labels:
        app: adopt
    spec:
      containers:
        - name: springboot-postgres-k8s
          image: 0109199416081991/mmv2-adopt-service:0.3.0-SNAPSHOT
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: adopt-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: adopt-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: adopt-db-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adopt-db-credentials
                  key: postgres_password
            - name: DB_PORT
              value: "5432"
            - name: SPRING_RABBITMQ_ADDRESSES
              value: "amqp://guest:guest@rabbitmq-0.rabbitmq.rabbits.svc.cluster.local:5672"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
            - name: RABBIT_URI
              value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local:5672"
            - name: EUREKA_URL
              value: "eureka-deployment-5b8f5cb49c-cqsz8.default.svc.cluster.local:5671"
#  kubectl port-forward adopt-deployment-6c44896968-7dr7k 8000:8000

