services:
  profile-db:
    container_name: profile-db
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: profile-db
    networks:
      - pet-corner

  adopt-db:
    container_name: adopt-db
    image: postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adopt-db
    networks:
      - pet-corner

  trainer-db:
    container_name: trainer-db
    image: postgres
    ports:
      - "5435:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trainer-db
    networks:
      - pet-corner


  sitting-db:
    container_name: sitting-db
    image: postgres
    ports:
      - "5434:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sitting-db
    networks:
      - pet-corner

  therapy-db:
    container_name: therapy-db
    image: postgres
    ports:
      - "5436:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: therapy-db
    networks:
      - pet-corner


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5051:80"
    networks:
      - pet-corner

  adopt-service:
    container_name: adopt-service
    image: 0109199416081991/mmv2-adopt-service:0.3.2-SNAPSHOT
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - adopt-db
      - naming-server
      - rabbitmq
    networks:
      - pet-corner
    environment:
      EUREKA_URL: http://naming-server:8761/eureka
      DB_PORT : 5432
      POSTGRES_PASSWORD : password
      POSTGRES_USER : admin
      DB_HOST : adopt-db
      DB_NAME : adopt-db
      ZIPKIN_URL: http://tracing-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672


  sitting-service:
    container_name: sitting-service
    image: 0109199416081991/mmv2-animal-sitting:0.3.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - "7000:7000"
    depends_on:
      - sitting-db
      - naming-server
      - rabbitmq
    networks:
      - pet-corner
    environment:
      EUREKA_URL: http://naming-server:8761/eureka
      DB_PORT : 5432
      POSTGRES_PASSWORD : password
      POSTGRES_USER : admin
      DB_HOST : sitting-db
      DB_NAME : sitting-db
      ZIPKIN_URL: http://tracing-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672

  training-service:
    container_name: training-service
    image: 0109199416081991/mmv2-animal-trainer:0.3.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - "6500:6500"
    depends_on:
      - trainer-db
      - naming-server
      - rabbitmq
    networks:
      - pet-corner
    environment:
      EUREKA_URL: http://naming-server:8761/eureka
      DB_PORT : 5432
      POSTGRES_PASSWORD : password
      POSTGRES_USER : admin
      DB_HOST : trainer-db
      DB_NAME : trainer-db
      ZIPKIN_URL: http://tracing-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672


  therapy-service:
    container_name: therapy-service
    image: 0109199416081991/mmv2-animal-therapy:0.3.2-SNAPSHOT
    restart: unless-stopped
    ports:
      - "6000:6000"
    depends_on:
      - therapy-db
      - naming-server
      - rabbitmq
    networks:
      - pet-corner
    environment:
      EUREKA_URL: http://naming-server:8761/eureka
      DB_PORT : 5432
      POSTGRES_PASSWORD : password
      POSTGRES_USER : admin
      DB_HOST : therapy-db
      DB_NAME : therapy-db
      ZIPKIN_URL: http://tracing-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672


  profile-service:
    container_name: profile-service
    image: 0109199416081991/mmv2-profile-service:0.3.2-SNAPSHOT
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - profile-db
      - naming-server
      - rabbitmq
    networks:
      - pet-corner
    environment:
      EUREKA_URL: http://naming-server:8761/eureka
      DB_PORT : 5432
      POSTGRES_PASSWORD : password
      POSTGRES_USER : admin
      DB_HOST : profile-db
      DB_NAME : profile-db
      ZIPKIN_URL: http://tracing-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672



  api-gateway:
    container_name: api-gateway
    image: 0109199416081991/mmv2-api-gateway:0.3.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    networks:
      - pet-corner
    environment:
      EUREKA_URL: http://naming-server:8761/eureka
      ZIPKIN_URL: http://tracing-server:9411/

  tracing-server:
    container_name: tracing-server
    image: openzipkin/zipkin:2.23
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - pet-corner
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.12-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pet-corner


  naming-server:
    container_name: naming-server
    image: 0109199416081991/mmv2-naming-server:0.1.0-SNAPSHOT
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - pet-corner

networks:
  pet-corner:
    driver: bridge