kind: Service
apiVersion: v1
metadata:
  name: training
  labels:
    name: training
spec:
  ports:
    - nodePort: 30650
      port: 6500
      targetPort: 6500
      protocol: TCP
  selector:
    app: training
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: training
spec:
  serviceName: "training"
  selector:
    matchLabels:
      app: training
  replicas: 3
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
        - name: training
          image: 0109199416081991/mmv2-animal-trainer:0.3.0-SNAPSHOT
          ports:
            - containerPort: 6500
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: training-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: training-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: training-db-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: training-db-credentials
                  key: postgres_password
            - name: DB_PORT
              value: "5432"
            - name: SPRING_RABBITMQ_ADDRESSES
              value: "amqp://guest:guest@rabbitmq-0.rabbitmq.rabbits.svc.cluster.local:5672"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
            - name: RABBIT_URI
              value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local:5672"
            - name: EUREKA_URL
              value: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka"
#  kubectl port-forward eureka-0 8761:8761

