kind: Service
apiVersion: v1
metadata:
  name: eureka-service
  labels:
    name: eureka-k8s
spec:
  ports:
    - nodePort: 30100
      port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: eureka
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka-k8s
          image: 0109199416081991/mmv2-naming-server:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8761

