kind: Service
apiVersion: v1
metadata:
  name: api-gateway
  labels:
    name: api-gateway
spec:
  ports:
    - nodePort: 30876
      port: 8765
      targetPort: 8765
      protocol: TCP
  selector:
    app: api-gateway
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-gateway
spec:
  serviceName: "api-gateway"
  selector:
    matchLabels:
      app: api-gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 0109199416081991/mmv2-api-gateway:0.3.0-SNAPSHOT
          ports:
            - containerPort: 8765
          env:
            - name: EUREKA_URL
              value: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka"
          #  kubectl port-forward eureka-0 8761:8761

#  kubectl port-forward api-gateway-0 8765:8765

